version: '3'
services:
  myubuntu:
    container_name: ubuntu
    image: ubuntu
    build:
      context: /Users/nishisingh/Desktop/Docker/ubu_dfile
    networks:
      - net
  remote_host:
    container_name: remote-host
    image: remote-host
    build:
      context: /Users/nishisingh/Desktop/Docker/Jenkins_Docker
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    platform: linux/amd64
    environment:
      - "MYSQL_ROOT_PASSWORD=1234"
    volumes:
      - "$PWD/db_data:/var/lib/mysql"
    networks:
      - net
networks:
  net: 
